name: Trivy Security Scan

on:
  push:
    branches:
      - main
  workflow_call:
    inputs:
      scanType:
        description: "Type of scan to perform (fs or image)"
        required: true
        type: string
      imageName:
        description: "Docker image to scan (for image scan type)"
        required: true
        type: string
        default: hello-world-python

jobs:
  trivy_scan:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository (required for filesystem scans)
      - name: Checkout Code
       
        uses: actions/checkout@v3

      # Setup cache for Trivy database
      - name: Setup Trivy Cache
        uses: actions/cache@v3
        with:
          path: trivy_cache
          key: trivy-db-cache

      # Install Trivy
      - name: Install Trivy
        run: |
          wget https://github.com/aquasecurity/trivy/releases/download/v0.52.0/trivy_0.52.0_Linux-64bit.deb
          sudo dpkg -i trivy_0.52.0_Linux-64bit.deb

      # Run Filesystem Scan
      - name: Run Filesystem Scan
        
        run: |
          export TRIVY_CACHE_DIR=$PWD/trivy_cache
          if [ -z "$(ls -A $TRIVY_CACHE_DIR)" ]; then
              echo "Trivy DB cache not found. Downloading the database..."
              trivy fs --scanners vuln -f json -o trivy-fs.json . > trivy-fs-report.json
          else
              echo "Using cached Trivy DB."
              trivy fs --scanners vuln --skip-db-update -f json -o trivy-fs.json . > trivy-fs-report.json
          fi

      # Run Image Scan
      - name: Run Image Scan
       
        run: |
          if [ -z "${{ inputs.imageName }}" ]; then
            echo "Error: imageName is required for image scans."
            exit 1
          fi

          export TRIVY_CACHE_DIR=$PWD/trivy_cache
          if [ -z "$(ls -A $TRIVY_CACHE_DIR)" ]; then
              echo "Trivy DB cache not found. Downloading the database..."
              trivy image -f json -o trivy-image.json hello-world-python > trivy-image-report.json
          else
              echo "Using cached Trivy DB."
              trivy image --skip-db-update -f json -o trivy-image.json hello-world-python > trivy-image-report.json
          fi

      - name: Upload Reports
        uses: actions/upload-artifact@v3
        with:
          name: trivy-reports
          path: |
            trivy-image-report.json
            trivy-fs-report.json
      # Upload Results to DefectDojo
     

