name: Trivy Security Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  trivy-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Trivy
      run: |
        curl -sfL https://github.com/aquasecurity/trivy/releases/download/v0.29.0/trivy_0.29.0_Linux-64bit.tar.gz | tar -xzv -C /usr/local/bin


    # Step 1: Build Docker image and scan for vulnerabilities
    - name: Build Docker image
      run: |
        docker build -t hello-world-python .

    - name: Scan Docker Image for vulnerabilities
      run: |
        trivy image --no-progress --exit-code 1 my-app-image:latest

    # Step 2: Scan filesystem for vulnerabilities
    - name: Scan Filesystem for vulnerabilities
      run: |
        trivy fs --no-progress --exit-code 1 .

    # Step 3: Scan Kubernetes Configs (Optional)
    - name: Scan Kubernetes YAML for misconfigurations
      run: |
        trivy config --no-progress --exit-code 1 ./k8s-configs/

    # Step 4: Scan for secrets in codebase (Optional)
    - name: Scan for Secrets in Codebase
      run: |
        trivy secrets --no-progress --exit-code 1 .
